vim.loader.enable()

require('user.plugins')
require('user.options')
require('user.folding')
require('user.keymaps')
require('user.preview')
require('user.colorscheme')
require('user.terminal')
require('user.icons')
require('user.lualine')
require('user.tabline')
require('user.lsp')
require('user.autosave')
require('user.autopairs')
require('user.indentscope')
